sudo: required

services:
- docker

language: java
dist: trusty

jdk:
- openjdk8

cache:
directories:
- $HOME/.m2

script:
- mvn clean package -U
- docker build -t oblacki/test-storitev:oblacek .

after_success:
- docker login -u="oblacki" -p="oblacki123"
- docker push oblacki/test-storitev:oblacek